Marius_Bauer
net-utilities/BigIPReport pull request #81
Opened 2021-09-28 13:51 UTC by Marius-Bauer93

removing mentioned errors and typos from the code.

2021-09-28 13:52 UTC, Marius-Bauer93 commented
@timriker Please let me know which details I need to add to the IProfile.ts file, do not what this is for. Thanks!

2021-10-01 17:17 UTC, timriker commented
please rename the .ts file back to a .ts file.

The js-src is where the "source code" to the javascript files lives. It's in TypeScript. The IProfile.ts file should describe the interface to the Profile such that typescript can validate it is being used correctly.

I run:

tsc --build tsconfig.json --verbose

to convert the js-src/*.ts files to underlay/js/*.js files. If I do this on your patch, all your js file edits will be reverted. Copy your edited into js-src/ then flush out the IProfile.ts interface file so syntax checking works. Then run tsc and validate that your changes are still there.

For local testing, I set my ReportRoot to "underlay" so I can test right in my working directory. I point apache at that directory so everything loads correctly.

2021-10-01 17:26 UTC, timriker commented
You added a new version in the comments. That's a Good Thing. You should also edit:

$Global:ScriptVersion in bigipreport.ps1
"Settings version" in bigipreportconfig.xml

so that the versions match.

2021-10-04 08:27 UTC, epacke requested changes

2021-10-04 08:27 UTC, epacke commented on js-src/SiteDataInterfaces/IProfile.ts
> +}
Missing new line, please add.

2021-10-04 08:27 UTC, epacke commented on underlay/js/bigipreport.js
> +	document.querySelector('div#policybutton').addEventListener('click', showPolicy);
Don't use tab for whitespace. Use spaces.

2021-10-04 08:27 UTC, epacke commented on underlay/js/bigipreport.js
> +		    case 'policy':
Replace tab here too. You can replace using regex by replacing `\t` with `    ` (space x4).

2021-10-04 08:27 UTC, epacke commented on underlay/js/bigipreport.js
> +		    case 'policy':
I see a few more but won't comment on this again to keep the review neat and tidy.

2021-10-04 08:28 UTC, epacke commented
Almost there Marius! :)

2022-01-29 20:22 UTC, merged